### ISSUE TITLE
Place Template work in seperate branch

### ISSUE THREAD

**Issue by memchk** [ZHU-ARTCC/Website#5]
@guisbonddev After some pestering from @mkosmo, I think we should begin putting your work in a separate branch, that we can merge in when ready. It will help with keeping the repo clean.

**Comment by guisbonddev** [comment]
Sounds good. I can just put it in my own Repo and we can worry about merging later. That way I don't have to worry about pushing to an external, if that's ok with you.

**Comment by memchk** [comment]
Not a problem. Just make sure I have access if you don't mind.

**Comment by guisbonddev** [comment]
Sounds good
